name: Python CLI Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'cli/python/**'
      - 'python/**'  # CLI depends on client library
      - '.github/workflows/python-cli-test.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'cli/python/**'
      - 'python/**'  # CLI depends on client library
      - '.github/workflows/python-cli-test.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # Fetch full history including tags for setuptools_scm
        fetch-depth: 0

    - name: Set up uv
      uses: astral-sh/setup-uv@v6

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install client library
      working-directory: python
      run: uv sync && uv build

    - name: Install CLI with dependencies
      working-directory: cli/python
      run: |
        uv sync
        uv add ../../python/dist/*.whl

    - name: Run CLI tests
      working-directory: cli/python
      run: uv run pytest

    - name: Test CLI functionality
      working-directory: cli/python
      run: |
        uv run restream.io --help
        uv run restream.io version